### ISSUE TITLE
codesearch indexing encountered performance cliff

### ISSUE THREAD

**Issue by staktrace** [livegrep/livegrep#226] opened 2019-04-20 20:01 UTC
We use the `codesearch` tool to index the mozilla-central repo daily. On Apr 4, the indexing took ~6.5 minutes. On Apr 5, the indexing took ~53 minutes. In between these two, stuff was added to the repository, of course, but nothing that should plausibly have caused an order-of-magnitude increase in indexing time. https://gist.github.com/staktrace/04137e7a5a297f3810c7cae74487088c shows the log snippets with times and codesearch stats output. Note that the `timer.index.dedup.hash` goes from 197710100 to 3001967457 (a 15x increase) and `timer.index.index_file` goes from 277013234 to 3088702832 (a 11x increase). All the other numbers seem to increase more reasonably.

This seems to imply that `codesearch` is hitting some sort of performance cliff with whatever new files were added to the repo between Apr 4 and Apr 5, and is causing the dedup.hash and index_file operations to take disproportionately longer. Before digging into the code to try and investigate, I was hoping somebody might have suggestions on where to start looking, or theories as to what is causing this.

**Comment by staktrace** [comment] 2019-04-20 20:07
Also, this issue might be intermittent since I have seen it on our production runs but not on my dev runs which should be basically identical (both run on c3.2xlarge AWS instances, etc.). Or time of day might be a factor, since I usually do my dev runs at different times than when the production runs happen. Not really sure.

**Comment by staktrace** [comment] 2019-04-20 20:16
Also, the above runs were based on a version of codesearch at rev 8b3d893f4dad92a788790394d6c9b4cf9f9eb520. So far I have one production run at a newer revision (44a30d47cad50d821daf97c858d3836f69a2e05b) and it seems to index at the "fast" speed. So maybe the issue has already been fixed, but I'd like to wait a few more days to see if it happens again.

**Comment by nelhage** [comment] 2019-04-20 20:47
I suspect this is fixed by https://github.com/livegrep/livegrep/commit/ea24af4f6be9aff095c5d399809eac7830e9cb8d which is in fact between the two commits you cited.

The problem is that I was keeping timers around ~every hash table lookup in the dedup hash table during indexing. If `gettimeofday` is backed by the VDSO, this is fine, since getting the current time is super fast. However, if your machine has switched to a clock source that isn't VDSO-backed (As best I can tell, on most virtualized environments this happens sometimes at ~random when the kernel decides the TSC clocksource is unstable, and distrusts it forever until next boot), then `gettimeofday` does a real syscall (maybe even ultimately a hypercall?), and becomes appreciably slow relative to a hash table lookup, and indexing time is dominated by the time it takes to keep metrics on it.

I used to have a `-D` option to disable these timers, but I decided it was easiest to just rip them out entirely and use `perf` and other tools if I needed to profile indexing.

I'm going to close this out since your description matches the above explanation (which I've observed previously as well) perfectly, but please feel free to re-open if it recurs post-ea24af4f6be9aff095c5d399809eac7830e9cb8d

**Closed by nelhage** 2019-04-20 20:47 UTC

**Comment by staktrace** [comment] 2019-04-21 13:45
That makes sense, thanks!
